init_cash = 100000.0
# 交易品类 stock / fund
kind = "stock"
data_path = "/Users/luoguochun/.config/bbq-trader/"
mongodb = "mongodb://localhost:27017"

[log]
level = "debug"
path = "/Users/luoguochun/.config/bbq-trader/logs"

[listen]
port = 9527

[fee]
broker = 0.00025
transfer = 0.00002
tax = 0.001


[push.email]
smtp_host = "smtp.126.com"
smtp_port = 465
user = "barbarianquant@126.com"
token = "DAZXJPKTVXRVOESQ"
notify = "buf1024@qq.com"

[push.wechat]
token = "SCT79912TBBpSAKVv98IdQ3RWqCoQQNW2"

[strategy]
monitor = ["/Users/luoguochun/.config/bbq-trader/strategy/monitor"]
strategy = ["/Users/luoguochun/.config/bbq-trader/strategy/strategy"]
broker = ["/Users/luoguochun/.config/bbq-trader/strategy/broker"]
risk = ["/Users/luoguochun/.config/bbq-trader/strategy/risk"]
